In [8]:

file = open("Cars2025.csv", "r")


#creating an empty list 
car_data = []

#iterating through each line in the file 
for line in file:
    line = line.strip()
    value = line.split(",")
    car_data.append(value)
file.close
print(car_data)


[['Maruti 800 AC', 'Maruti Zen Estilo VXI BSIV', 'Hyundai Elite i20 Sportz Plus CVT BSIV', 'Mahindra Bolero 2011-2019 SLX', 'Hyundai i10 Magna 1.1L', 'Hyundai i20 1.4 CRDi Magna', 'Nissan Terrano XV D Premium AMT', 'Volvo V40 D3 R-Design', 'Chevrolet Sail LT ABS', 'Maruti Swift VDI BSIV', 'Hyundai Grand i10 1.2 Kappa Sportz BSIV', 'Tata Nexon 1.5 Revotorq XM', 'Renault Duster 85PS Diesel RxL Optional', 'Mercedes-Benz New C-Class C 220 CDI Elegance AT', 'Maruti SX4 S Cross 2015-2017 DDiS 200 Zeta', 'Hyundai i20 Active 1.4 SX', 'Tata Indica Vista Quadrajet VX', 'Maruti Ertiga VDI', 'Maruti Alto 800 VXI', 'Mahindra XUV500 W9 BSIV', 'Honda Jazz V CVT', 'Toyota Innova 2.5 G (Diesel) 8 Seater', 'Ford Figo Diesel ZXI', 'Hyundai Verna CRDi 1.6 SX Option', 'Maruti Swift Vdi BSIII', 'Toyota Innova 2.5 EV (Diesel) PS 7 Seater BS IV', 'Maruti Swift VDI BSIV', 'Tata Nexon 1.2 Revotron XZ Plus Dual Tone', 'Volvo XC40 D4 Inscription BSIV', 'Maruti Alto LXi', 'Maruti Alto LX', 'Maruti Alto LX BSIII', 

<div style="padding:10,0,10,0;">
    <h3>Lab assessment!</h3>
    <p>You have 1 hour to finish this assessment and submit it through the submission link on Canvas.</p>
    <p>It's expected of you to use type annotations for inputs and outputs of functions, and docstrings using the google style to create a documentation for your <strong>functions</strong> only. All functions should have a try-except structure to validate the input and should raise an error otherwise. Non-compliance will result in points deduction.</p>
    <p>Using the internet or genAI to answer the questions will be considered a breach of conduct.</p>
</div>

<div><p><strong>Question 1 <span style="color:blue">(10% marks)</span></strong> - Load the car dataset into a file object using the standard Python file loader, no other methods will be allowed. In this file, every row will contain data regarding the following:</p>
    <ol start=0>
        <li>Name <span style="color:blue;font-size:.7em;">(String)</span>.</li>
        <li>Year <span style="color:red;font-size:.7em;">(Integer)</span>.</li>
        <li>Selling price <span style="color:red;font-size:.7em;">(Integer)</span>.</li>
        <li>Km driven <span style="color:red;font-size:.7em;">(Integer)</span>.</li>
        <li>Fuel <span style="color:blue;font-size:.7em;">(String)</span>.</li>
        <li>Seller type <span style="color:blue;font-size:.7em;">(String)</span>.</li>
        <li>Transmission <span style="color:orange;font-size:.7em;">(Binary)</span>.</li>
        <li>Owner <span style="color:blue;font-size:.7em;">(String)</span></li>
        <li>Mileage <span style="color:red;font-size:.7em;">(Integer)</span>.</li>
        <li>Engine <span style="color:blue;font-size:.7em;">(String)</span>.</li>
        <li>Max power <span style="color:red;font-size:.7em;">(Integer)</span>.</li>
        <li>Torque <span style="color:blue;font-size:.7em;">(String)</span>.</li>
        <li>Seats <span style="color:red;font-size:.7em;">(Float)</span></li>    
        <li>Make <span style="color:blue;font-size:.7em;">(String)</span>.</li>
        <li>Model <span style="color:blue;font-size:.7em;">(String)</span></li>
    </ol>
<p>Iterate through the object and append its content into a list, then save each row of this dataset into a variable named after it using positional indexes and the <strong>.split(",")</strong> method.</p></div>

<div>
    <p><strong>Question 2 <span style="color:blue">(10% marks)</span></strong> - Write a program that counts and the number of cars for each fuel type category. The function should accept a single argument, the list containing the fuel information, and should return a dictionary with the fuel type as keys and the count as values.</p>
</div>

In [9]:
from typing import List, Dict

def fuel_type(fuel_list:List[str]) -> Dict[str, int]:
    ''''creating a function for counting the cars with different fuel types
    Args:  
        fuel_list:List[str]: list containing the fuel type
    Returns:  
        Dict[str, int] : Dictionary with fuel type as keys and count as values
    '''
    fuel_counts= {}

    for fuel in fuel_list:
        fuel_counts[fuel] = fuel_counts.get(fuel,0)+1
        ##petrol, diesel, petrol

    return fuel_counts
data = fuel_type(car_data[4])
print (data)

    

{'Petrol': 429, 'Diesel': 559, 'CNG': 7, 'LPG': 5}


<div>
    <p><strong>Question 3 <span style="color:blue">(10% marks)</span></strong> - Write a function to calculate the percentage of tramission types of that particular Make for a given year. The function should accept two arguments, the make (e.g, "Toyota") and the year (e.g, 1984) and return a string containing the pertinent information</p>
</div>

<div style="padding:10,0,10,0;">
<p><strong>Question 4 <span style="color:blue">(15% marks)</span></strong> - Write a function that will accept an integer as input to print the following output when considering an integer of 5 (5 elements):</p>

<p>*<br>
**<br>
***<br>
****<br>
*****<br>
****<br>
***<br>
**<br>
*</p>

<p>This question needs to be solved using <strong>Iteration structures</strong> alone.</p>
</div>

In [7]:
def star_pattern(n: int) -> None:
    """
    Prints a star pattern based on the given integer.
    """
    try:
        if not isinstance(n, int):
            raise TypeError("Input must be an integer.")
        
        for i in range(1, n + 1):
            print("*" * i)
        for i in range(n - 1, 0, -1):
            print("*" * i)

    except Exception as e:
        print(f"Error: {e}")
        
star_pattern(5)

*
**
***
****
*****
****
***
**
*


<div style="padding:10,0,10,0;">
    <p><strong>Question 5 <span style="color:blue">(total 25% marks)</span></strong> -Use <strong>Numpy</strong> for the following tasks:
        <p>Create a 1-dimensional array with 25 values using the standard_normal method. Reshape it into a 5×5 matrix and then replace all numbers smaller than 0 in the matrix with -1. <strong>(10% marks)</strong></p>
    <p>Calculate the exponent of each element in the array and assign this value to a new array. <strong>(10% marks)</strong></p>
    <p>Finally, calculate the dot product of the first array against the second array. <strong>(5% marks)</strong></p>

</div>

In [34]:
import numpy as np
array_a = np.random.standard_normal(25)

matrix_a = array_a.reshape(5,5)
print (matrix_a)

[[ 1.28623602 -0.9691378  -0.13559831 -1.28691253 -0.75817946]
 [ 0.95259196  1.66497256 -1.36228543 -0.45864891 -0.66202243]
 [ 2.2158017  -1.77256646  0.70489547 -0.27051222 -0.32043488]
 [ 0.2244358   0.52843246 -0.34696646  0.60617036  0.36206664]
 [-1.19260026 -0.53875596  2.00804017 -1.08889299 -0.81257586]]


In [37]:
array_c =np.random.standard_normal(5)
print(array_c.shape)

(5,)


In [27]:
matrix_a[matrix_a <0] = -1
matrix_b = np.exp(matrix_a)
print(matrix_b)

[[1.20373718 0.36787944 0.36787944 2.90457044 0.36787944]
 [3.22242331 0.36787944 0.36787944 0.36787944 1.04542317]
 [0.36787944 1.40821987 0.36787944 0.36787944 0.36787944]
 [4.28692091 1.04287318 0.36787944 1.394589   1.38758009]
 [1.16153017 0.36787944 0.36787944 1.66096004 1.93321469]]


In [28]:
dot = np.dot(matrix_a,matrix_b)
dot

array([[ 0.04245896, -0.96376192, -0.64315754, -0.37109137, -1.79874448],
       [-6.41709307, -2.37216253, -0.65682836,  1.34217051, -2.2845378 ],
       [-5.91694714, -3.06091709, -1.34558292, -6.20206408, -3.69867771],
       [ 3.32581988, -0.38994021,  0.42589747,  4.88327207,  1.30623587],
       [-0.4692293 , -0.9493639 , -0.25151245,  1.50165369,  0.62017998]])

<div style="padding:10,0,10,0;">
    <p><strong>Question 6 <span style="color:blue">(Total 30% marks)</span></strong> - Create a Three-dimensional "Random walk" function called randomWalk. The function should have a single parameter (The number of steps) and return a dictionary with the following: the key should be the step dimension <strong style="color:blue;">X</strong>, <strong style="color:red;">Y</strong> or <strong style="color:purple;">Z</strong>, and the value should list with the steps in that dimension <strong>(15% marks)</strong>.</p>
<p>Create a second function called euclidian_distance to calculate the distance between the initial and final position <strong>(10% marks)</strong>. The function has to use the initial and final coordinates and the following formulae:</p>
</div>

$$ distance(i,f) = {\sqrt{(s1-f1)^2+(s2-f2)^2+(s3-f3)^2}} $$

<p>Where:</p>
<ul>
    <li>s and f stands for starting and final positions</li>
</ul>
<p>Import the module "Assignment2" and use the function plot3d. This function will accept your dictionary as input <strong>(5% marks)</strong>.</p>
</div>

In [33]:
import numpy as np 
def randomWalk(steps: int) -> dict:
    """
    Generates a 3D random walk of given steps.
    """
    try:
        if not isinstance(steps, int):
            raise TypeError("Steps must be an integer.")
        # Start at origin (0,0,0)
        x = np.cumsum(np.random.choice([-1, 1], steps))
        y = np.cumsum(np.random.choice([-1, 1], steps))
        z = np.cumsum(np.random.choice([-1, 1], steps))
        return {"X": x.tolist(), "Y": y.tolist(), "Z": z.tolist()}
    except Exception as e:
        print(f"Error: {e}")

def euclidian_distance(start: tuple, end: tuple) -> float:
    """
    Calculates Euclidean distance between start and end 3D points.
    """
    try:
        if not (len(start) == len(end) == 3):
            raise ValueError("Points must have 3 coordinates.")
        return float(np.sqrt(sum((s - f) ** 2 for s, f in zip(start, end))))
    except Exception as e:
        print(f"Error: {e}")

walk = randomWalk(5)
print(walk)


{'X': [-1, 0, -1, 0, 1], 'Y': [1, 0, -1, -2, -1], 'Z': [1, 0, 1, 0, 1]}
